name: mpflutter_build_tools
description: The MPFlutter Build Tools

version: 2.6.5

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ">=1.8.0"
  yaml_edit: ^2.1.1
  es_compression: ^2.0.12
  dio: ">=5.0.0"
